# 机场订阅
proxy-providers:
  airport:
    url: https://a.a.a/
    type: http
    interval: 43200
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 1000
    proxy: DIRECT

# 全局配置
mixed-port: 7890
socks-port: 7891
port: 7892
redir-port: 7893
tproxy-port: 7894
external-controller: 127.0.0.1:9999
secret: ""
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true # 开启统一延迟，也就是看起来好看一点，没什么实际作用
tcp-concurrent: true # 启用 TCP 并发连接，将会使用 dns 解析出的所有 IP 地址进行连接，使用第一个成功的连接
# interface-name: enp6s18
# routing-mark: 6666 # 标记出内核的流量
log-level: silent
find-process-mode: "off"
disable-keep-alive: false #在 Android 强制为 true, 关闭心跳包的发送，减少耗电
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# 入站
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  device: utun
  dns-hijack:
    - any:53
    - tcp://any:53
  #使用nikki，混入全部不修改的情况，开启接口指定为nikki
  #使用仅内核自行修改下面三项为true
  #device: nikki
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
  # 设置绕过clash的流量
  # route-exclude-address-set:
  #   - fakeip-filter
  #   - cn
  #   - private

# 嗅探
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.push.apple.com"

# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  # 可选值 fake-ip/redir-host，默认redir-host
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:fakeip_filter,cn,private,custom_direct"

  nameserver-policy:
    # 用于广告拦截，的话就不能开启 direct-nameserver-follow-policy: true
    # 如果开启, direct-nameserver 的优先级就会低于 nameserver-policy
    # 这样的话, 不论如何设置广告的路由, 都会导致优先匹配nameserver-policy, 也就是说 广告会一直过滤, 导致开关无效

    # 为了不触发某些应用的 fallback 机制, 所以返回 rcode://success
    "rule-set:ads,custom_reject":
      - rcode://success

    # direct-nameserver-follow-policy: true 不开启的话, 下面这个2个规则其实都没有什么用了,都会优先走 direct-nameserver
    # 可以注释掉

    # "rule-set:private,cn":
    #   - 222.172.200.68
    #   - 61.166.150.123

    # "rule-set:custom_direct,networktest,trackerslist,microsoft_cn,apple_cn,google_cn,games_cn":
    #   - https://223.5.5.5/dns-query#ecs=222.172.200.68/24&ecs-override=true
    #   - https://223.6.6.6/dns-query#ecs=222.172.200.68/24&ecs-override=true

  # 用于解析DNS服务器的域名
  default-nameserver:
    - https://223.5.5.5/dns-query#ecs=222.172.200.68/24&ecs-override=true
    - https://223.6.6.6/dns-query#ecs=222.172.200.68/24&ecs-override=true

    # - https://1.12.12.12/dns-query
    # - https://120.53.53.53/dns-query

  # 代理节点域名解析服务器，仅用于解析代理节点的域名
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query#ecs=222.172.200.68/24&ecs-override=true
    - https://223.6.6.6/dns-query#ecs=222.172.200.68/24&ecs-override=true
    # - https://8.8.8.8/dns-query#ecs=222.172.200.68/24&ecs-override=true
    # - https://8.8.4.4/dns-query#ecs=222.172.200.68/24&ecs-override=true
    # - https://doh.pub/dns-query#ecs=222.172.200.68/24&ecs-override=true

  # direct-nameserver-follow-policy: true  # 如果开启这个配置 direct-nameserver 的优先级会低于 nameserver-policy
  # 用于 direct 出口域名解析的 DNS 服务器
  direct-nameserver:
    - system
    - 222.172.200.68
    - 61.166.150.123
    - 223.6.6.6
    - 223.5.5.5

  # 不要用 fallback ，在解析的时候会同时使用 nameserver 和 fallback ，造成DNS泄露
  nameserver:
    - https://8.8.8.8/dns-query#ecs=222.172.200.68/24&ecs-override=true
    - https://8.8.4.4/dns-query#ecs=222.172.200.68/24&ecs-override=true
    # - https://101.101.101.101/dns-query
    # - https://101.102.103.104/dns-query
    # - https://1.1.1.1/dns-query
    # - https://1.0.0.1/dns-query

auto_test: &auto_test { type: url-test, tolerance: 30, interval: 300, timeout: 1000, include-all: true, url: https://www.gstatic.com/generate_204 }

proxy-groups:
  - { name: 🚀 节点选择, type: select, proxies: [♻️ 自动选择, ✋ 手动选择] }
  - { name: ✋ 手动选择, type: select, include-all: true }

  - { <<: *auto_test, name: ♻️ 自动选择 }
  - { <<: *auto_test, name: 💡 AI节点, exclude-filter: "(?i)🏴‍☠️|❓|其他|other|🇭🇰|港|hk|hong ?kong|🇷🇺|俄罗斯|ru|Russia" }

  - { name: 🚫 广告, type: select, proxies: [🔴 拒绝, 🟢 直连] } # 域名
  - { name: 🎮 游戏CN, type: select, proxies: [🟢 直连, 🚀 节点选择] } # 域名
  - { name: Ⓜ️ 微软CN, type: select, proxies: [🟢 直连, 🚀 节点选择] } # 域名
  - { name: 🌈 谷歌CN, type: select, proxies: [🟢 直连, 🚀 节点选择] } # 域名
  - { name: 🍎 苹果CN, type: select, proxies: [🟢 直连, 🚀 节点选择] } # 域名
  - { name: 📋 BT下载, type: select, proxies: [🟢 直连, 🚀 节点选择] } # 域名
  - { name: 📈 网络测试, type: select, proxies: [🟢 直连, 🚀 节点选择, ✋ 手动选择] } # 域名
  - { name: 🤖 AI!CN, type: select, proxies: [💡 AI节点, 🚀 节点选择, ✋ 手动选择, 🟢 直连] } # 域名
  - { name: 🌍 媒体!CN, type: select, proxies: [🚀 节点选择, ✋ 手动选择, 🟢 直连] } # 域名 + IP
  - { name: 🕹️ 游戏!CN, type: select, proxies: [🚀 节点选择, ✋ 手动选择, 🟢 直连] } # 域名 + IP
  - { name: 📲 电报!CN, type: select, proxies: [🚀 节点选择, ✋ 手动选择, 🟢 直连], hidden: true } # IP
  - { name: 🧱 海外FB, type: select, proxies: [🚀 节点选择, 🟢 直连] } # 域名
  - { name: 🏠 国内FB, type: select, proxies: [🟢 直连, 🚀 节点选择] } # 域名 + IP
  - { name: 🔐 私有网络, type: select, proxies: [🟢 直连], hidden: true } # 域名 + IP
  - { name: 🐟 漏网之鱼, type: select, proxies: [🚀 节点选择, 🟢 直连] }
  - { name: 🟢 直连, type: select, proxies: [DIRECT], hidden: true }
  - { name: 🔴 拒绝, type: select, proxies: [REJECT], hidden: true }

rules:
  # - AND,((DST-PORT,443),(NETWORK,UDP)),(NOT,(RULE-SET,cn)),REJECT # 屏蔽国外的QUIC连接
  - RULE-SET,custom_proxy,🧱 海外FB
  - RULE-SET,custom_direct,🏠 国内FB
  - RULE-SET,custom_reject,🚫 广告
  - RULE-SET,ads,🚫 广告
  - RULE-SET,networktest,📈 网络测试
  - RULE-SET,private,🔐 私有网络
  - RULE-SET,trackerslist,📋 BT下载
  - RULE-SET,microsoft_cn,Ⓜ️ 微软CN
  - RULE-SET,apple_cn,🍎 苹果CN
  - RULE-SET,google_cn,🌈 谷歌CN
  - RULE-SET,games_cn,🎮 游戏CN
  - RULE-SET,ai,🤖 AI!CN
  - RULE-SET,games,🕹️ 游戏!CN
  - RULE-SET,media,🌍 媒体!CN
  - RULE-SET,tld_proxy,🧱 海外FB
  - RULE-SET,proxy,🧱 海外FB
  - RULE-SET,cn,🏠 国内FB
  - RULE-SET,private_ip,🔐 私有网络,no-resolve
  - RULE-SET,cn_ip,🏠 国内FB
  - RULE-SET,media_ip,🌍 媒体!CN
  - RULE-SET,telegram_ip,📲 电报!CN,no-resolve
  - MATCH,🐟 漏网之鱼

rule-anchor:
  domain: &domain { type: http, interval: 86400, behavior: domain, format: mrs }
  ip: &ip { type: http, interval: 86400, behavior: ipcidr, format: mrs }
  class: &class { type: http, interval: 86400, behavior: classical, format: yaml }

rule-providers:
  fakeip_filter: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs" }
  private: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.mrs" }
  ads: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ads.mrs" }
  trackerslist: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/trackerslist.mrs" }
  microsoft_cn: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.mrs" }
  apple_cn: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.mrs" }
  google_cn: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs" }
  games_cn: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games-cn.mrs" }
  media: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/media.mrs" }
  games: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games.mrs" }
  ai: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs" }
  networktest: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/networktest.mrs" }
  tld_proxy: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/tld-proxy.mrs" }
  proxy: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs" }
  cn: { <<: *domain, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs" }
  private_ip: { <<: *ip, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs" }
  cn_ip: { <<: *ip, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs" }
  media_ip: { <<: *ip, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/mediaip.mrs" }
  telegram_ip: { <<: *ip, url: "https://github.boki.moe/https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs" }
  custom_proxy: { <<: *class, url: "https://github.boki.moe/https://raw.githubusercontent.com/zsjsll/proxy-config/refs/heads/dist/rules/proxy.yaml" }
  custom_direct: { <<: *class, url: "https://github.boki.moe/https://raw.githubusercontent.com/zsjsll/proxy-config/refs/heads/dist/rules/direct.yaml" }
  custom_reject: { <<: *class, url: "https://github.boki.moe/https://raw.githubusercontent.com/zsjsll/proxy-config/refs/heads/dist/rules/reject.yaml" }
