name: Run CLI

on:
  push:
    branches:
      - clash
  workflow_dispatch:
    inputs: # (可选) 定义手动输入的参数
      environment:
        description: "选择部署环境"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      debug_mode:
        description: "开启调试模式?"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_FORMAT: ${{ vars.IS_FORMAT }}
      PROVIDER_URLS: ${{ secrets.PROVIDER_URLS }}
      DELETE_PROPERTY: '["tun","global_anchor"]'

      COMMIT_MESSAGE: "Deploy artifacts from ${{ github.sha }} [skip ci]"
      REPO_URL: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Build project
        shell: sh
        run: |
          bun run cli
