name: 🔧 Run CLI and deploy to gist

on:
  push:
    branches:
      - clash
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_FORMAT: false
      PROVIDER_URLS: ${{ secrets.PROVIDER_URLS }}
      DELETE_PROPERTY: '["tun","global_anchor"]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Build clash config
        shell: sh
        run: |
          bun run cli

      - name: Deploy to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ec4b27f6ee5736e3d60da5d2dc0dbcad
          file_path: dist
